replicaCount: 1

image:
  registry: swr.af-south-1.myhuaweicloud.com
  org: george
  name: ecommerce-product
  tag: "27dc492a4b5845fd9d9facca470c50a76c98e9e0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: default-secret

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"

service:
  port: 8082
  targetPort: 80
  type: ClusterIP

containerPort: 80
