replicaCount: 1

image:
  registry: swr.af-south-1.myhuaweicloud.com
  org: george
  name: ecommerce-product
  tag: "b8e735cdaae188025ad90d06e33e35cd35b6a40e"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: default-secret

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"

service:
  port: 8082
  targetPort: 80
  type: ClusterIP

containerPort: 80
