apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
  annotations:
    kubernetes.io/elb.id: <your-elb-id>
    kubernetes.io/elb.ip: <your-elb-ip>
    kubernetes.io/elb.class: performance
    kubernetes.io/elb.listen-ports: '443' #ELB Listener port

spec:
  ingressClassName: cce   # Huawei LoadBalancer ingress uses CCE class

  tls:
  - hosts:
    - admin-board.geoajdemos.com.ng
    - eshop.geoajdemos.com.ng
    secretName: wildcard-geoademos-tls

  rules:
  - host: admin-board.geoajdemos.com.ng
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-dashboard-app
            port:
              number: 80

  - host: eshop.geoajdemos.com.ng
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecommerce-app
            port:
              number: 80